# Generated by Django 5.2 on 2025-07-21 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarabe', '0002_account_delete_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='materials/')),
                ('status', models.CharField(choices=[('good', 'Good'), ('under_maintenance', 'Under Maintenance'), ('pending_maintenance', 'Pending Maintenance')], max_length=30)),
                ('type', models.CharField(choices=[('vehicle', 'Vehicle'), ('tool', 'Tool')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('inspection_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('year_of_manufacture', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('current_mileage', models.PositiveIntegerField()),
                ('fuel_level', models.PositiveIntegerField()),
                ('oil_level', models.PositiveIntegerField()),
                ('tire_status', models.CharField(choices=[('new', 'New'), ('worn', 'Worn'), ('flat', 'Flat')], max_length=20)),
                ('body_condition', models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged')], max_length=20)),
                ('engine_status', models.CharField(choices=[('good', 'Good'), ('faulty', 'Faulty')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('Diesel', 'Diesel'), ('Gasoline', 'Gasoline'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], default='Diesel', max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scarabe.material')),
            ],
        ),
    ]
