# Generated by Django 5.2 on 2025-07-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarabe', '0003_material_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='materials/'),
        ),
    ]
