# Generated by Django 5.2 on 2025-07-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarabe', '0004_alter_material_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='body_condition',
            field=models.CharField(choices=[('good', 'Bon'), ('damaged', 'Endommagé')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_status',
            field=models.CharField(choices=[('good', 'Bon'), ('faulty', 'Défaillant')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Gasoline', 'Essence'), ('Electric', 'Électrique'), ('Hybrid', 'Hybride')], default='Diesel', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='tire_status',
            field=models.CharField(choices=[('new', 'Neuf'), ('worn', 'Usé'), ('flat', 'Crevé')], max_length=20),
        ),
    ]
