# Generated by Django 5.2 on 2025-07-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarabe', '0005_alter_vehicle_body_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('good', 'Bon'), ('under_maintenance', 'En maintenance'), ('pending_maintenance', 'Maintenance en attente')], max_length=30),
        ),
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('vehicle', 'Véhicule'), ('tool', 'Outil')], max_length=20),
        ),
    ]
