# Generated by Django 5.2 on 2025-07-22 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarabe', '0006_alter_material_status_alter_material_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tool', to='scarabe.material')),
            ],
        ),
    ]
