# Generated by Django 5.2 on 2025-07-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarabe', '0007_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='reservationStatus',
            field=models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Réservé')], max_length=20, null=True),
        ),
    ]
