# Generated by Django 5.2 on 2025-07-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarabe', '0008_material_reservationstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='reservationStatus',
            field=models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Réservé')], default='available', max_length=20),
        ),
    ]
