# Generated by Django 5.2 on 2025-07-24 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarabe', '0009_alter_material_reservationstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Malfunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('Low', 'Faible'), ('Medium', 'Moyenne'), ('High', 'Élevée'), ('Critical', 'Critique')], default='Medium', max_length=10)),
                ('status', models.CharField(choices=[('Reported', 'Signalé'), ('In Progress', 'En cours'), ('Resolved', 'Résolu')], default='Reported', max_length=15)),
                ('reported_by', models.CharField(max_length=100)),
                ('declared_date', models.DateField(auto_now_add=True)),
                ('declared_time', models.TimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scarabe.material')),
            ],
        ),
        migrations.CreateModel(
            name='MalfunctionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='malfunctions/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('malfunction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='scarabe.malfunction')),
            ],
        ),
    ]
