# Generated by Django 5.2 on 2025-07-24 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarabe', '0010_malfunction_malfunctionphoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='malfunction',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_malfunctions', to=settings.AUTH_USER_MODEL),
        ),
    ]
