# Generated by Django 5.2 on 2025-07-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scarabe', '0011_alter_malfunction_reported_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='malfunctionphoto',
            old_name='image',
            new_name='photo',
        ),
    ]
