# Generated by Django 5.2 on 2025-07-24 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarabe', '0012_rename_image_malfunctionphoto_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('Low', 'Faible'), ('Medium', 'Moyenne'), ('High', 'Élevée')], default='Medium', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='advertisements/covers/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='advertisements/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
