# Generated by Django 5.2 on 2025-07-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarabe', '0015_alter_malfunction_updated_at_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
