# Generated by Django 5.2 on 2025-07-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarabe', '0016_reservation_end_time_reservation_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(null=True),
        ),
    ]
