# Generated by Django 5.2 on 2025-07-27 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarabe', '0018_reservation_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(auto_now_add=True)),
                ('check_time', models.TimeField(auto_now_add=True)),
                ('car_body_ok', models.BooleanField(blank=True, help_text='Carrosserie en bon état', null=True)),
                ('tires_ok', models.BooleanField(blank=True, help_text='Pneus en bon état', null=True)),
                ('lighting_ok', models.BooleanField(blank=True, help_text='Éclairage fonctionnel', null=True)),
                ('next_service_within_1k', models.BooleanField(blank=True, help_text='Prochaine révision < 1000\xa0km', null=True)),
                ('adblue_ok', models.BooleanField(blank=True, help_text='Liquide AdBlue suffisant', null=True)),
                ('no_warning_lights', models.BooleanField(blank=True, help_text='Aucun voyant allumé', null=True)),
                ('clean_vehicle', models.BooleanField(blank=True, help_text='Véhicule propre', null=True)),
                ('docs_present', models.BooleanField(blank=True, help_text='Documents présents', null=True)),
                ('report', models.TextField(blank=True, help_text='Inspecteur’s written report', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_prechecks', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prechecks', to='scarabe.reservation')),
            ],
        ),
    ]
