# Generated by Django 5.2 on 2025-08-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarabe', '0020_supportticket_supportreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='reservationStatus',
            field=models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Réservé'), ('not_available', 'Hors service')], default='available', max_length=20),
        ),
    ]
