# Generated by Django 5.2 on 2025-08-11 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scarabe', '0022_alter_supportreply_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='user',
        ),
    ]
