# Generated by Django 5.2 on 2025-08-13 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarabe', '0024_remove_supportreply_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportreply',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
