# Generated by Django 5.2 on 2025-08-16 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarabe', '0025_supportreply_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
