# Generated by Django 5.2 on 2025-08-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarabe', '0026_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('active', 'Activé'), ('expired', 'Expiré')], default='active', max_length=20),
        ),
    ]
