# Generated by Django 5.2 on 2025-08-17 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarabe', '0028_advertisement_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('notification_date', models.DateField()),
                ('notification_time', models.TimeField()),
                ('notification_status', models.CharField(choices=[('unread', 'Non lue'), ('read', 'Lue')], db_index=True, default='unread', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scarabe.account')),
            ],
        ),
    ]
