# Generated by Django 5.2 on 2025-08-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scarabe', '0030_notification_title_alter_notification_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='category',
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'Ouvert'), ('resolved', 'Résolu')], db_index=True, default='open', help_text='Statut du ticket (ouvert / résolu)', max_length=20),
        ),
    ]
